# Generated by Django 5.1.5 on 2025-01-26 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_tasks_delete_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
